#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

jobs:
- job: linux64
  timeoutInMinutes: 120
  pool:
    vmImage: "ubuntu-latest"
  steps:
  - bash: |
      docker run -d --name ubuntu -v $PWD:/Qt i386/ubuntu:18.04 tail -f /dev/null
      docker exec -t ubuntu bash -c "cd /Qt/..;
                                     apt-get update;
                                     apt-get -y install sudo git;
                                     git clone https://github.com/omega-gg/Qt;
                                     cd Qt;
                                     sh build.sh linux"
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Qt-linux64
