#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
- job: win32
  timeoutInMinutes: 360
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      sh build.sh win32
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Qt-win32

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

#- job: macOS
#  timeoutInMinutes: 360
#  pool:
#    vmImage: "macOS-latest"
#  steps:
#  - bash: |
#      sh build.sh macOS
#  - publish: $(System.DefaultWorkingDirectory)/deploy
#    artifact: Qt-macOS

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

#- job: linux64
#  timeoutInMinutes: 360
#  pool:
#    vmImage: "ubuntu-latest"
#  steps:
#  - bash: |
#      docker run -d --name ubuntu -v $PWD:/Qt i386/ubuntu:18.04 tail -f /dev/null
#      docker exec -t ubuntu bash -c "cd /Qt/..;
#                                     apt-get update;
#                                     apt-get -y install sudo git;
#                                     git clone https://github.com/omega-gg/Qt;
#                                     cd Qt;
#                                     sh build.sh linux"
#  - publish: $(System.DefaultWorkingDirectory)/deploy
#    artifact: Qt-linux64
