#--------------------------------------------------------------------------------------------------
# Windows
#--------------------------------------------------------------------------------------------------

jobs:
#- job: win32
#  timeoutInMinutes: 360
#  pool:
#    vmImage: "windows-latest"
#  steps:
#  - bash: |
#      cd ..
#      git clone https://github.com/omega-gg/3rdparty
#      cd 3rdparty
#      bash generate.sh win32
#      cd ../s
#      sh build.sh win32
#  - publish: $(System.DefaultWorkingDirectory)/deploy
#    artifact: Qt-win32

- job: win64
  timeoutInMinutes: 360
  pool:
    vmImage: "windows-latest"
  steps:
  - bash: |
      cd ..
      git clone https://github.com/omega-gg/3rdparty
      cd 3rdparty
      bash generate.sh win64
      cd ../s
      sh build.sh win64
  - publish: $(System.DefaultWorkingDirectory)/deploy
    artifact: Qt-win64

#--------------------------------------------------------------------------------------------------
# macOS
#--------------------------------------------------------------------------------------------------

#- job: macOS
#  timeoutInMinutes: 360
#  pool:
#    vmImage: "macOS-latest"
#  steps:
#  - bash: |
#      sh build.sh macOS
#  - publish: $(System.DefaultWorkingDirectory)/deploy
#    artifact: Qt-macOS

#--------------------------------------------------------------------------------------------------
# Linux
#--------------------------------------------------------------------------------------------------

#- job: linux32
#  timeoutInMinutes: 360
#  pool:
#    vmImage: "ubuntu-latest"
#  steps:
#  - bash: |
#      docker run -d --name ubuntu -v $PWD:/Qt i386/ubuntu:18.04 tail -f /dev/null
#      docker exec -t ubuntu bash -c "cd /Qt/..;
#                                     apt-get update;
#                                     apt-get -y install sudo git;
#                                     git clone https://github.com/omega-gg/Qt;
#                                     cd Qt;
#                                     sh build.sh linux"
#  - publish: $(System.DefaultWorkingDirectory)/deploy
#    artifact: Qt-linux32

#- job: linux64
#  timeoutInMinutes: 360
#  pool:
#    vmImage: "ubuntu-latest"
#  steps:
#  - bash: |
#      docker run -d --name ubuntu -v $PWD:/Qt amd64/ubuntu:18.04 tail -f /dev/null
#      docker exec -t ubuntu bash -c "cd /Qt/..;
#                                     apt-get update;
#                                     apt-get -y install sudo git;
#                                     git clone https://github.com/omega-gg/Qt;
#                                     cd Qt;
#                                     sh build.sh linux"
#  - publish: $(System.DefaultWorkingDirectory)/deploy
#    artifact: Qt-linux64
